### ISSUE TITLE
ti.healthkit module source code

### ISSUE THREAD

**Issue by moizchhatriwala** [BIDMCDigitalPsychiatry/LAMP-app#1]
Hello,
Can I get titanium ti.healthkit module source code. I see that module is used within the app you posted, but If you can share the module source code it will be great

**Comment by michaelmenon** [comment]
Currently we are using “com.zco.healthKitIOS” module for fetching health kit data. Module Source code is upload to the below GitHub path. 

tree/master/com.zco.healthKitIOS_sourceCode
