### ISSUE TITLE
Notifications are no longer working.

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-app#2]
On both Android and iOS devices.

**Comment by cchoertz** [comment]
Are the notifications not working at all or is it that they are not being sent on time ?

**Comment by michaelmenon** [comment]
Are the notifications not working at all or is it that they are not being sent on time ?

**Comment by avaidyam** [comment]
It appears they are not working at all for some (all?) devices we have tested.

**Comment by moizchhatriwala** [comment]
Hello Aditya,
Can I get titanium ti.healthkit module source code. I see that module is used within the app you posted, but If you can share the module source code it will be great

**Comment by michaelmenon** [comment]
Ok thanks Aditya, can you let me know the device models you tested. We are checking on it and will update asap.

**Comment by avaidyam** [comment]
Notifications seem to work again on Android devices in my testing!
